global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Prometheus itself, assuming it runs on localhost:9090

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']  # Node Exporter, for host-related metrics

  - job_name: 'nginx'
    static_configs:
      - targets: ['localhost:9113']  # Nginx Prometheus Exporter, change this to the IP of your Nginx exporter instance
